### ISSUE TITLE
Fix Folder structure

### ISSUE THREAD

**Issue by GentikSolm** [BKulmala/Kulmala#1]
Fix folder structure, the project should be in the base directory of the git repo

**Comment by supsa-ak** [comment]
Hi, I can change folder structure of your project. I am participating in hacktoberfest.

**Comment by GentikSolm** [comment]
Thank you for the offer @supsa-ak 
Im working with another student from my university on his portfolio site, and am having him fix up these issues. He will be working solo on all the issues for this repo.

**Comment by supsa-ak** [comment]
Ok. No problem btw if you face any feature or bug let me know.
