### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by GentikSolm** [BKulmala/Kulmala#6]
javascript is a pain to work with. Typescript gives type safety to JS, which helps catch lots of runtime errors before they happen.

**Comment by BKulmala** [comment]
Getting this to work was more of a pain than the JavaScript itself. Just can't get it done.

**Comment by GentikSolm** [comment]
In order to get TS to work, you'll need to look at webpack to compile your TS to JS. you could also look into bun or deno. Essentially you will code in TS, then "compile" TS to a raw js bundle which ships with your site
